### ISSUE TITLE
Adding a Host or Domain cause ad blocking stop working

### ISSUE THREAD

**Issue by lexer98** [britannic/blacklist#10]
Every time I try to use this command "set service dns forwarding blacklist include ****" or " set service dns forwarding blacklist domains include *****" to blacklist a website that have p0rn ads. The adblocking stop working when I reset the device, not sure what is wrong so I had to reinstall the .deb package to make it working again. I tried even hard reset the device and configure it from scratch same problem
My device is a ER-X with 1.10.8

**Comment by britannic** [comment]
@lexer98, please explain what you mean by "reset". FYI, the config integration tree directories aren't persisted with a hard (factory) reset, but will persist over reboots.  If the blacklisting isn't already reinstalled automatically ([see this repo for a solution](https://github.com/britannic/install-edgeos-packages)) after a reset or upgrade, any blacklisting configuration will be lost after an upgrade or hard reset.

**Comment by lexer98** [comment]
Sorry english is not very good. I mean "Reboot" not reset, the adblock works perfect with the default setting when I try to add a hosts.txt or make any modification after a reboot the ad blocking stop working. 
I upgraded to 1.10.9 and still have the same problem

**Comment by britannic** [comment]
@lexer98, are you saving your configuration? Here's an example of how to do that:

```
configure
set service dns forwarding blacklist exclude cdn.visiblemeasures.com
set service dns forwarding blacklist include www.nastywebsites.com
commit
save
exit
```

If the configuration isn't saved and only committed, it won't persist after a reboot.

**Comment by lexer98** [comment]
Yes, but the configuration no only not persist also the default setting don't work anymore. 
This is what I do
>Login to SSH 
>configure
>set service dns forwarding blacklist domains include javhd.com
>commit
>save
>exit 
>exit
>reboot - The changes don't apply instantly so I try to reboot and then nothing works

**Comment by britannic** [comment]
@lexer98, since the changes aren't applying immediately, then you have an issue with the configuration. Rebooting won't fix issues with configuration. Recommend you post a description of your issue and configuration at: [Ubiquiti Community](https://community.ubnt.com/t5/EdgeRouter/DNS-Adblocking-amp-Blacklisting-dnsmasq-Configuration/m-p/2692431#M242496)

**Comment by blastik** [comment]
FYI @britannic this issue happened exactly to me. i did `set service dns forwarding blacklist domains include adomain.com` and all the sudden no ads were blocked any longer. tried to restart, no luck.
log shows:
```
ubnt@EdgeRouter-X-5-Port:/etc/dnsmasq.d$ tail /var/log/update-dnsmasq.log
INFO[004]2021-04-21 09:18:35.488: blacklisted-subdomains: extracted: 1
INFO[005]2021-04-21 09:18:35.488: blacklisted-subdomains: dropped: 0
INFO[006]2021-04-21 09:18:35.504: whitelisted-subdomains: downloaded: 1
INFO[007]2021-04-21 09:18:35.505: whitelisted-subdomains: extracted: 1
INFO[008]2021-04-21 09:18:35.505: whitelisted-subdomains: dropped: 0
NOTI[009]2021-04-21 09:18:35.515: Total entries found: 2
NOTI[00a]2021-04-21 09:18:35.515: Total entries extracted 2
NOTI[00b]2021-04-21 09:18:35.515: Total entries dropped 0
INFO[00c]2021-04-21 09:18:36.035: Successfully restarted dnsmasq
NOTI[00d]2021-04-21 09:18:36.036: Blacklist update completed......
ubnt@EdgeRouter-X-5-Port:/etc/dnsmasq.d$ sudo /config/scripts/update-dnsmasq -v
NOTI[001]09:23:47.601: Starting blacklist update...
INFO[002]09:23:47.637: Checking for stale blacklists...
INFO[003]09:23:47.657: blacklisted-subdomains: downloaded: 1
INFO[004]09:23:47.658: blacklisted-subdomains: extracted: 1
INFO[005]09:23:47.659: blacklisted-subdomains: dropped: 0
INFO[006]09:23:47.676: whitelisted-subdomains: downloaded: 1
INFO[007]09:23:47.677: whitelisted-subdomains: extracted: 1
INFO[008]09:23:47.677: whitelisted-subdomains: dropped: 0
NOTI[009]09:23:47.687: Total entries found: 2
NOTI[00a]09:23:47.688: Total entries extracted 2
NOTI[00b]09:23:47.689: Total entries dropped 0
INFO[00c]09:23:48.600: Successfully restarted dnsmasq
NOTI[00d]09:23:48.601: Blacklist update completed......
```

**Comment by blastik** [comment]
tried to `delete service dns forwarding blacklist domains include adomain.com` commit;save;exit;reboot and no luck. still does not work :(

**Comment by blastik** [comment]
```show service dns forwarding
 blacklist {
     disabled false
     dns-redirect-ip 0.0.0.0
     domains {
         exclude concierge.analytics.console.aws.a2z.com
     }
 }
 cache-size 150
 listen-on switch0
```

**Comment by blastik** [comment]
do i need to configure this ? https://github.com/britannic/blacklist#how-do-i-configure-dnsmasq

**Comment by blastik** [comment]
ok i did all the steps see my current conf:

```
ubnt@EdgeRouter-X-5-Port# show service dns forwarding
 blacklist {
     disabled false
     dns-redirect-ip 0.0.0.0
     domains {
         exclude concierge.analytics.console.aws.a2z.com
     }
 }
 cache-size 2048
 except-interface pppoe0
 name-server 1.1.1.1
 name-server 1.0.0.1
 options bogus-priv
 options enable-ra
 options expand-hosts
 options localise-queries
 options strict-order
 system
 ```
 
 ```
ubnt@EdgeRouter-X-5-Port# show system name-server
 name-server 127.0.0.1
 name-server ::1
```
 still no luck

**Comment by blastik** [comment]
ok so i fixed it by uninstalling.
in my case i've had configured [this](https://github.com/britannic/blacklist#how-do-i-keep-my-usg-configuration-after-an-upgrade-provision-or-reboot) so i didnt need to do anything else to install it back. after a reboot adblocking was again working for me.

**Comment by britannic** [comment]
> ok i did all the steps see my current conf:
> 
> ```
> ubnt@EdgeRouter-X-5-Port# show service dns forwarding
>  blacklist {
>      disabled false
>      dns-redirect-ip 0.0.0.0
>      domains {
>          exclude concierge.analytics.console.aws.a2z.com
>      }
>  }
>  cache-size 2048
>  except-interface pppoe0
>  name-server 1.1.1.1
>  name-server 1.0.0.1
>  options bogus-priv
>  options enable-ra
>  options expand-hosts
>  options localise-queries
>  options strict-order
>  system
> ```
> 
> ```
> ubnt@EdgeRouter-X-5-Port# show system name-server
> name-server 127.0.0.1
> name-server ::1
> ```
> 
> still no luck

@blastik, for future reference, your configuration as posted above, didn't have any ad-blocking sources, so no IP redirects would have occurred.

**Comment by blastik** [comment]
@britannic for the record. i know that no ad-blocking sources were in the output but thats they way i found it. i havent really do anything that could make this impact. in fact it happened to me again after upgrading to the latest firmware.
im pretty sure there is a bug around but anyway i got it working.
