### ISSUE TITLE
Problem on router restarts

### ISSUE THREAD

**Issue by mgoreiro** [britannic/blacklist#11]
Hi..

First at all thanks; works perfect!!!

But I have a little problem; everytime the router reboots the script does not start and I have to uninstall and then reinstall....

¿Any sugestion?

**Comment by britannic** [comment]
@mgoreiro, I'll more information on the EdgeOS version, what isn't starting and any error messages.

**Comment by britannic** [comment]
I'm closing this, reopen if unresolved by v1.1.7.4.

**Comment by mgoreiro** [comment]
Sorry, all day out of home :)

I'll try the new version; any problem will be reported!
