### ISSUE TITLE
apt fails to download sources

### ISSUE THREAD

**Issue by ndfred** [britannic/blacklist#12]
I followed the [setup instructions on the github page](https://britannic.github.io/blacklist/#installation) and am seeing the deb repo 404:

> $ sudo apt-get update && sudo apt-get install edgeos-dnsmasq-blacklist
> Ign https://raw.githubusercontent.com britannic Release.gpg
> Ign https://raw.githubusercontent.com britannic Release
> Err https://raw.githubusercontent.com britannic/main mips Packages
>   The requested URL returned error: 404
> Ign https://raw.githubusercontent.com britannic/main Translation-en
> W: Failed to fetch https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/dists/britannic/main/binary-mips/Packages  The requested URL returned error: 404
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> admin@Router:~$ sudo apt-get update && sudo apt-get install edgeos-dnsmasq-blacklist
> Ign https://raw.githubusercontent.com britannic Release.gpg
> Ign https://raw.githubusercontent.com britannic Release
> Err https://raw.githubusercontent.com britannic/main mips Packages
>   The requested URL returned error: 404
> Ign https://raw.githubusercontent.com britannic/main Translation-en
> W: Failed to fetch https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/dists/britannic/main/binary-mips/Packages  The requested URL returned error: 404
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> I went back to downloading and installing the deb file manually but there may be an issue with either documentation or the published repo file.

I went back to downloading and installing the deb file manually but there may be an issue with either documentation or the published repo file.

See corresponding [UBNT forum post](https://community.ubnt.com/t5/EdgeRouter/DNS-Adblocking-amp-Blacklisting-dnsmasq-Configuration/m-p/2758529/highlight/true#M249586)

**Comment by britannic** [comment]
Fixed with latest build [b214df2](https://github.com/britannic/blacklist/commit/b214df2ab59ef82033bc1f49e4c064d5ce88d656).

**Comment by cmcginty** [comment]
Just got the same error. Was the fix released?

**Comment by ndfred** [comment]
Same here, this is what I am seeing, apparently the Release file is missing as well so probably worth adding:

> $ sudo apt-get update
> Ign https://raw.githubusercontent.com britannic Release.gpg
> Ign https://raw.githubusercontent.com britannic Release
> Err https://raw.githubusercontent.com britannic/main mips Packages
>   The requested URL returned error: 404
> Ign https://raw.githubusercontent.com britannic/main Translation-en
> W: Failed to fetch https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/dists/britannic/main/binary-mips/Packages  The requested URL returned error: 404
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.

caliban on the forum is seeing similar error messages (copy pasting his output from `sudo apt update`):

> Ign:1 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist britannic InRelease
> Err:2 https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist britannic Release
> 404 Not Found
> Reading package lists... Done
> E: The repository 'https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist britannic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by britannic** [comment]
Repo is fixed now.

**Comment by ndfred** [comment]
Nice, thanks @britannic! Now we just need to update [the installation documentation](https://britannic.github.io/blacklist/#installation) to reflect the new repo name:

> configure
> set system package repository blacklist components main
> set system package repository blacklist description 'Britannic blacklist debian wheezy repository'
> set system package repository blacklist distribution wheezy
> set system package repository blacklist url 'https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/'
> commit;save;exit

**Comment by britannic** [comment]
I'm leaving it as wheezy, since the underlying repo builder (reprepro) is too delicate and involved to make quick changes.
