### ISSUE TITLE
Consider removing youtubeadsblacklist

### ISSUE THREAD

**Issue by h-m-f-t** [britannic/blacklist#19]
[youtubeadsblacklist](https://github.com/anudeepND/youtubeadsblacklist/) hasn't seen an update in nearly 2 years. When I leave this source in the config, Youtube ads _are_ blocked – but, unfortunately, so are Youtube videos. Removing the source re-enables playback.

cc: @anudeepND

**Comment by britannic** [comment]
Removed! Thank you for raising this issue.
