### ISSUE TITLE
ReloadDNS():  error: fork/exec /bin/bash: cannot allocate memory

### ISSUE THREAD

**Issue by mono-ped** [britannic/blacklist#22]
# commit
[ service dns forwarding blacklist ]
NOTI[001]17:59:48.086: Starting blacklist update...
INFO[002]17:59:48.090: Removing stale blacklists...
INFO[003]17:59:48.162: blacklisted-subdomains: downloaded: 15
INFO[004]17:59:48.165: blacklisted-subdomains: extracted: 15
INFO[005]17:59:48.170: blacklisted-subdomains: dropped: 0
INFO[006]17:59:48.199: blacklisted-servers: downloaded: 2
INFO[007]17:59:48.203: blacklisted-servers: extracted: 2
INFO[008]17:59:48.206: blacklisted-servers: dropped: 0
INFO[009]17:59:48.302: global-whitelisted-domains: downloaded: 99
INFO[00a]17:59:48.304: global-whitelisted-domains: extracted: 99
INFO[00b]17:59:48.306: global-whitelisted-domains: dropped: 0
INFO[00c]17:59:48.355: whitelisted-servers: downloaded: 1
INFO[00d]17:59:48.358: whitelisted-servers: extracted: 1
INFO[00e]17:59:48.361: whitelisted-servers: dropped: 0
INFO[00f]17:59:48.365: Downloading domains source zeus
INFO[010]17:59:48.375: Downloading domains source NoBitCoin
INFO[011]17:59:48.378: Downloading domains source SmartTVblacklist
INFO[012]17:59:48.380: Downloading domains source malwaredomains.com
INFO[013]17:59:48.382: Downloading domains source notrackingDomains
INFO[014]17:59:48.385: Downloading domains source simple_tracking
INFO[015]17:59:56.374: simple_tracking: downloaded: 34
INFO[016]17:59:56.405: simple_tracking: extracted: 34
INFO[017]17:59:56.427: simple_tracking: dropped: 0
INFO[018]17:59:56.652: SmartTVblacklist: downloaded: 198
INFO[019]17:59:56.688: SmartTVblacklist: extracted: 175
INFO[01a]17:59:56.740: SmartTVblacklist: dropped: 23
INFO[01b]17:59:57.454: NoBitCoin: downloaded: 689
INFO[01c]17:59:57.473: NoBitCoin: extracted: 677
INFO[01d]17:59:57.496: NoBitCoin: dropped: 12
INFO[01e]18:00:14.422: malwaredomains.com: downloaded: 26885
INFO[01f]18:00:14.441: malwaredomains.com: extracted: 26881
INFO[020]18:00:14.448: malwaredomains.com: dropped: 4
INFO[021]18:00:42.422: Downloading hosts source githubSteveBlack
INFO[022]18:00:42.424: Downloading hosts source YoutubeAdBlockList
INFO[023]18:00:42.425: Downloading hosts source notracking
INFO[024]18:00:42.426: Downloading hosts source YoutubeBlockList
INFO[025]18:00:42.429: Downloading hosts source sysctl.org
INFO[026]18:00:42.434: Downloading hosts source openphish
INFO[027]18:00:44.465: YoutubeBlockList: downloaded: 69
INFO[028]18:00:44.488: YoutubeBlockList: extracted: 69
INFO[029]18:00:44.523: YoutubeBlockList: dropped: 0
INFO[02a]18:00:49.713: openphish: downloaded: 2558
INFO[02b]18:00:49.716: openphish: extracted: 1136
INFO[02c]18:00:49.744: openphish: dropped: 1422
INFO[02d]18:01:03.362: YoutubeAdBlockList: downloaded: 8882
INFO[02e]18:01:03.376: YoutubeAdBlockList: extracted: 8848
INFO[02f]18:01:03.378: YoutubeAdBlockList: dropped: 34
INFO[030]18:01:13.825: sysctl.org: downloaded: 20567
INFO[031]18:01:13.846: sysctl.org: extracted: 17576
INFO[032]18:01:13.847: sysctl.org: dropped: 2991
INFO[033]18:01:28.178: notracking: downloaded: 39080
INFO[034]18:01:28.180: notracking: extracted: 22628
INFO[035]18:01:28.183: notracking: dropped: 16452
INFO[036]18:01:29.625: githubSteveBlack: downloaded: 42353
INFO[037]18:01:29.689: githubSteveBlack: extracted: 27137
INFO[038]18:01:29.694: githubSteveBlack: dropped: 15216
NOTI[039]18:01:32.742: Total entries found: 141432
NOTI[03a]18:01:32.745: Total entries extracted 105278
NOTI[03b]18:01:32.748: Total entries dropped 36154
ERRO[03c]18:01:32.753: ReloadDNS():
 error: fork/exec /bin/bash: cannot allocate memory

Everything worked well out of the box.
I've only added a couple of extra sources.
After adding https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt i started getting an error while trying to commit

**Comment by britannic** [comment]
Your router has run out of memory. Are you running this on an ER-X or what? Run `free -h` and see how much free memory you have. Try rebooting as well.
