### ISSUE TITLE
Server Certificate Verification Failed

### ISSUE THREAD

**Issue by tlsnine** [britannic/blacklist#24]
Just updated to v1.10.10 of the ER firmware and tried to install adblocking via apt-get method but I'm getting the following:

> Ign https://raw.githubusercontent.com wheezy Release.gpg
> Ign https://raw.githubusercontent.com wheezy Release
> Err https://raw.githubusercontent.com wheezy/main mips Packages
>   server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> Ign https://raw.githubusercontent.com wheezy/main Translation-en
> W: Failed to fetch https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/dists/wheezy/main/binary-mips/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.

I was able to manually download ind install the .deb file, but only by passing a -k argument to the curl download, then letting dpkg do its thing.
I haven't really tested anything else at this point.  Just informing of the issues...

Thanks for all the hard work!

**Comment by britannic** [comment]
@tlsnine, did you follow the directions on adding the signing key before installing using apt-get? Also, you should be using the latest release:  v1.1.7.8

**Comment by tlsnine** [comment]
I followed your instructions in order as they appear on github.

Whenever I attempt to add the key, I get:

trace@ubnt:~$ sudo curl -L https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/public.key | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate is not yet valid
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.
gpg: no valid OpenPGP data found.


I’ve attempted this command with the -k and I get:

trace@ubnt:~$ sudo curl -k -L https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/public.key | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3112  100  3112    0     0  10003      0 --:--:-- --:--:-- --:--:-- 12806
gpg: key 5273D52C was created 99278413 seconds in the future (time warp or clock problem)
gpg: key 5273D52C was created 99278413 seconds in the future (time warp or clock problem)
gpg: key 5273D52C was created 99278413 seconds in the future (time warp or clock problem)
gpg: key 5273D52C was created 99278413 seconds in the future (time warp or clock problem)
OK

**Comment by tlsnine** [comment]
Does this have anything to do with the underlying EdgeMax software being moved to Stretch from Wheezy?
Again, my firmware is 1.10.10 now.

**Comment by tlsnine** [comment]
Closing this as ID10T on my side...
My ER4 wasn't grabbing the correct time from my NTP server. (weird!)
I had to manually run "set date ntp" and everything fell into place after that.
My bad.
Thanks!
