### ISSUE TITLE
YouTube 

### ISSUE THREAD

**Issue by CarloPSW** [britannic/blacklist#26]
Hi,
I have installed blacklists on my router and I am not clear about two aspects:
how can I check if the service is active and working?
I saw the advertising on YouTube continues to be there (less frequent than before) how can I check?

Many Thanks

**Comment by britannic** [comment]
Youtube bypasses DNS for adverts, by embedding actual IP addresses for links - so dnsmasq's FQDN to IP remap won't work. Testing depends on the lists you're using, google "how do I test adblocking" or pick a blacklisted FQDN and use nslookup/dig/host to check it. Recommend you visit the [Ubiquiti community conversation](https://community.ui.com/questions/DNS-Adblocking-and-Blacklisting-dnsmasq-Configuration-Integration-Package-v1-1-8-1/eb05f1b2-5316-4a80-8221-5e8b02575da4) and ask your questions there.
