### ISSUE TITLE
Minor suggestion: emphasise difference between gateway and controller for "make permanent" instructions

### ISSUE THREAD

**Issue by ConradHughes** [britannic/blacklist#3]
Thanks very much for this: initial installation was a breeze, and I'm really looking forward to seeing how well it works over the next while.

One minor suggestion I have is with regard to the "How can I keep my USG configuration" FAQ entry:

  https://github.com/britannic/blacklist#how-do-can-keep-my-usg-configuration-after-an-upgrade-provision-or-reboot

.. I think it might help those coming to this for the first time if you add a bullet point noting that the config.gateway.json file is to be obtained from the *gateway*, but stored on the *controller*.  This is of course what the Ubiquiti instructions say, but it's an easy detail to miss if you're just skim-reading, since all of the other work needed to install is just done on the gateway.

**Comment by britannic** [comment]
Appreciate the feedback and donation Conrad! Let me know if the README update addresses your suggested revision - feel free to submit your own wording if not.

**Comment by ConradHughes** [comment]
Looks good — might be inclined to emphasise/bold "controller" since it's that change of context which is the "surprise" I skimmed past.  Otherwise great — thanks again!
