### ISSUE TITLE
Whitelist source

### ISSUE THREAD

**Issue by JonathanTroyer** [britannic/blacklist#30]
Currently, there is no way (that I can tell) to add a source file as a whitelist. This would save time manually entering commonly whitelisted domains, such as [annudeepND's whitelist](https://github.com/anudeepND/whitelist).

**Comment by britannic** [comment]
Thanks for highlighting this use case. You're welcome to make pull request and create the functionality. I don't have time to do that myself at present. More info [here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) if you need assistance on making a [PR](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).
