### ISSUE TITLE
can´t commit

### ISSUE THREAD

**Issue by killertrust** [britannic/blacklist#31]
hi
just update the black list on my edgerouter but now won´t let me commit 
I add and exclution but gime and update error say no internet access but pretty sure the router have internet
try to reboot the router same problem try disable the blacklist but can´t 

![blacklist error](https://user-images.githubusercontent.com/71734496/93942457-ab52cb00-fced-11ea-91c1-a12b2ce22ac6.JPG)

**Comment by britannic** [comment]
@killertrust, please post your question on the [Ubiquiti EdgeRouter forum](https://community.ui.com/questions/DNS-Adblocking-and-Blacklisting-dnsmasq-Configuration-Integration-Package-v1-2-4-2/eb05f1b2-5316-4a80-8221-5e8b02575da4), there is also a large body of help content there.
