### ISSUE TITLE
Debian repo is inaccessible

### ISSUE THREAD

**Issue by weili-jiang** [britannic/blacklist#33]
When fetching [the debian repo](https://raw.githubusercontent.com/britannic/debian-repo/master/blacklist/public/), I get a 400 error.

**Comment by britannic** [comment]
The repo has moved, did you follow the instructions [here](https://github.com/britannic/blacklist#apt-get-installation---erlite-3-erpoe-5-er-x-er-x-sfp-er4-unifi-gateway-3--unifi-gateway-4)? Make sure your package sources match those in the FAQ.

**Comment by weili-jiang** [comment]
Hmm thanks, I didn't realise that the URL was not accessible except via apt. Sorry to bother you.
