### ISSUE TITLE
`/etc/init.d/dnsmasq restart` failed when trying to whitelist

### ISSUE THREAD

**Issue by helinwang** [britannic/blacklist#35]
I found notion.so was blacklisted:
```
/etc/dnsmasq.d/hosts.openphish.blacklist.conf:address=/www.notion.so/0.0.0.0
```
So I followed the readme, added the following to `/etc/dnsmasq.conf`:
```
address=/www.notion.so/# 
```
But then the following command fails:
```
$ sudo /etc/init.d/dnsmasq restart
[....] Restarting dnsmasq (via systemctl): dnsmasq.serviceJob for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
 failed!
```
`sudo journalctl -xe` does not show anything.

Is this the right way to whitelist? Thank you!

**Comment by britannic** [comment]
@helinwang, not sure what system you're working on. Recommend you post your question to the Ubiquiti EdgeRouter thread at [community.ui.com](https://community.ui.com/questions/DNS-Adblocking-and-Blacklisting-dnsmasq-Configuration-Integration-Package-v1-2-4-5/eb05f1b2-5316-4a80-8221-5e8b02575da4).
