### ISSUE TITLE
Blocks Slack attachments

### ISSUE THREAD

**Issue by fitzage** [britannic/blacklist#36]
For some reason a recent update has prompted Slack to not be able to upload or download attachments, because it blocks files.slack.com.

After using little snitch to see what slack was accessing, I whitelisted files.slack.com, and the problem was fixed.

This is an easy fix, but it’s a very odd thing to block, and could really confuse some other people who are probably pestering Slack support about it.

**Comment by britannic** [comment]
@fitzage, your blocklist sources are responsible for any redirection that dnsmasq makes. Do check in with the [Ubiquiti community](https://community.ui.com/questions/DNS-Adblocking-and-Blacklisting-dnsmasq-Configuration-Integration-Package-v1-2-4-5/eb05f1b2-5316-4a80-8221-5e8b02575da4) and share any issues concerning specific sources.
