### ISSUE TITLE
bug + github page mismatch ?

### ISSUE THREAD

**Issue by blastik** [britannic/blacklist#37]
hello!

first, thank you so much for this work. it really rocks! I've sent to your paypal a 🍺  for that good work 😉  

i wanted to give you a couple of heads up in care you are not aware.

1. i could reproduce [this issue](https://github.com/britannic/blacklist/issues/10) opened some time ago, i've added to that thread some information. if you want my help to fix that bug just tell me.
2. by https://britannic.github.io/blacklist/ it seems that there is a newer release but it does not appear in https://github.com/britannic/blacklist/releases 

thanks!

**Comment by britannic** [comment]
Thanks for the feedback, I have pushed the tag and created the release to match the docs.
