### ISSUE TITLE
Commit local blacklist file without Internet access?

### ISSUE THREAD

**Issue by nonPointer** [britannic/blacklist#38]
CLI commands:
```cli
configure
set service dns forwarding blacklist hosts source myhosts file /config/user-data/antiad.txt
commit
```
Logs:
```log
NOTI[001]21:51:22.197: Starting blacklist update...
CRIT[002]21:51:25.199: No internet access, aborting blacklist update!
```

**Comment by britannic** [comment]
Please post to the [Ubiquiti community](https://community.ui.com/questions/DNS-Adblocking-and-Blacklisting-dnsmasq-Configuration-Integration-Package-v1-2-4-5/eb05f1b2-5316-4a80-8221-5e8b02575da4) for input on your issue. You can reopen this, if the community helps you determine you have found a bug.
