### ISSUE TITLE
Remove ads from youtube app on TV

### ISSUE THREAD

**Issue by bisha77** [britannic/blacklist#39]
Hi , 

Thank you for your wonderful tool , It has really helped me to get rid of annoying ads in my PCs and other devices. 
I do wonder if there is a way to get rid of ADs from youtube TV ap . 

Regards

**Comment by britannic** [comment]
Hello @bisha77. No, since YouTube bypasses DNS lookups and embeds direct IP address in their video streams to prevent blocking.
