### ISSUE TITLE
troubleshooting

### ISSUE THREAD

**Issue by blastik** [britannic/blacklist#46]
hello there!
sometimes i get some legit content blocked when im navigating from my mobile phone while connected to the wireless.
im wondering if I could output some logs in order to troubleshoot blacklisting to be able to make exceptions. because in the computer browser certainly i can enable developer tools and see the domains being blocked but in the mobile phone im not sure how to proceed since some content might be inside an app. any ideas?
thanks!

**Comment by britannic** [comment]
Hi @blastik, please post your question in the [community.ui.com thread](https://community.ui.com/questions/DNS-Adblocking-and-Blacklisting-dnsmasq-Configuration-Integration-Package-v1-2-4-5/eb05f1b2-5316-4a80-8221-5e8b02575da4), as issues are only used to track and resolve coding bugs.
