### ISSUE TITLE
'The specified configuration node is not valid' when setting global domain

### ISSUE THREAD

**Issue by ozinfotech** [britannic/blacklist#47]
I went to globally include a domain and got an error.
`#  set service dns forwarding blacklist include zefirka.net`
`The specified configuration node is not valid`
`Set failed`

If I changed the command to `#  set service dns forwarding blacklist include domains zefirka.net` then it worked. Any ideas why it wouldn't work globally?

**Comment by britannic** [comment]
Hi @ozinfotech, please post your question in the [community.ui.com thread](https://community.ui.com/questions/DNS-Adblocking-and-Blacklisting-dnsmasq-Configuration-Integration-Package-v1-2-4-5/eb05f1b2-5316-4a80-8221-5e8b02575da4), as issues are only used to track and resolve coding bugs.
