### ISSUE TITLE
false positive with hostsfile.org

### ISSUE THREAD

**Issue by rmoriz** [britannic/blacklist#5]
http://www.hostsfile.org/Downloads/hosts.txt

contains

```
127.0.0.1	www.crunchbase.com
```

which is an obvious false-positive.

I've added it to my local whitelist using:

```
configure
set service dns forwarding blacklist exclude www.crunchbase.com
commit;save;exit
```

**Comment by britannic** [comment]
This isn't an issue with the update-dnsmasq blacklisting parser/configuration builder. The source [http://www.hostsfile.org/Downloads/hosts.txt](http://www.hostsfile.org) is where the false positive is coming from. You will need to notify [them](http://www.hostsfile.org) or as you have already, whitelist the false positive.

**Comment by rmoriz** [comment]
True, however in the name of "sane defaults", I just wanted to point out, that hostsfile.org is probably not a sane default list.

**Comment by rmoriz** [comment]
If someone else runs into this:

I ended up with removing the hostsfile list:

```
configure
delete service dns forwarding blacklist hosts source hostsfile.org
commit;save;exit
```

I used grep to detect the origin of a block , e.g.:

```
grep -r "de.aliexpress.com"  /etc/dnsmasq.d
/etc/dnsmasq.d/hosts.hostsfile.org.blacklist.conf:address=/de.aliexpress.com/0.0.0.0
```
