### ISSUE TITLE
FAQ Cleanup suggestion

### ISSUE THREAD

**Issue by Amoeba00** [britannic/blacklist#55]
Since the [malwaredomains](https://www.malwaredomainlist.com) list has been stale and removed from the package, might be a good idea to remove/update the hyperlinks in the FAQ and/or replace it with a current list or replace the name with an obvious fake.

The No Coin Filter list is current, follows the same structure, and is still in the default package.
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

**Comment by britannic** [comment]
@Amoeba00 v1.2.4.8 has been released with FAQ clean up.
