### ISSUE TITLE
Time for an update build?

### ISSUE THREAD

**Issue by Amoeba00** [britannic/blacklist#56]
Lots of folks are posting problems with the ERX units and it's a definite result of those two primary lists, OISD and Steve Black, growing so large.

Here are the default results from package installs:
July 2022:  Total entries extracted 136104
Today:       Total entries extracted 234118

I think it makes sense to remove one of them and then update the FAQ with a special ERX/ERX-SFP section with the commands that users can copy/paste if they want to remove/add the other.

Removing Steve Black / Keeping OISD
Total entries extracted 59691

Removing OISD / Keeping Steve Black
Total entries extracted 194322

Also, as an aside, I was curious about the simple_tracking list with the 34 domains.  It appears that while the [disconnect.me](https://disconnect.me/) site and [browser extension](https://github.com/disconnectme) hasn't been updated in quite a while, they do have a [json file that gets updated more frequently](https://github.com/disconnectme/disconnect-tracking-protection).  
What's even stranger is that when I remove it from the default package, I get a "Total entries extracted 234360," and putting it back the number goes back down to 234118.  Just thought, I pass that one.

Thanks again for all your work on this!  Cheers!

**Comment by britannic** [comment]
@Amoeba00, the package would need to have JSON parsing added to get the [disconnect.me](https://disconnect.me/) lists. You're welcome to create a pull request and add the functionality. Otherwise, I can just remove [disconnect.me](https://disconnect.me/) from the initial install.

**Comment by britannic** [comment]
@Amoeba00 v1.2.4.8 has been released.
