### ISSUE TITLE
<FEATURE REQUEST> dns-redirect-host

### ISSUE THREAD

**Issue by BenchPressesBooks** [britannic/blacklist#6]
Would it be possible to have blocked requests redirected to a URL or DNS entry, such as blocked.mysite.com? This way should a user click a google sponsored link (for example) instead of the page turning white because the traffic was sinkholed, an internal web server could display a page letting them know what happened.

**Comment by britannic** [comment]
dnsmasq will send back the redirect IP address you configured as your blackhole. Providing your "blocked.mysite.com" IP is static, you can set that IP as the redirect.
