### ISSUE TITLE
Things still blocked even after uninstall

### ISSUE THREAD

**Issue by jimr6007** [britannic/blacklist#8]
First I tried the cli commands to disable and then a complete uninstall.
Cleared browser cache, tried different browsers on different computers.
No Ad block extensions are installed.

But, Ads are still being blocked. I even restarted my router.

I needed to do some testing but I can't do that if I'm unable to disable it.

ERL-3
Linux ubnt 3.10.107-UBNT #1 SMP Mon Oct 1 11:07:12 UTC 2018 mips64 GNU/Linux

Thanks !

**Comment by jimr6007** [comment]
if I point a client directly at 8.8.8.8 for example the problem goes away so no doubt it's something funny with dnsmasq on my router after I installed and subsequently uninstalled this package.

**Comment by britannic** [comment]
You have a router configuration issue, since uninstalling reproduced the problem. Closing issue.

**Comment by jimr6007** [comment]
"You have a router configuration issue"

ummm,  no ...

I have a "third party package left a bunch of configs after remove/purge" issue.

problem is "apt-get remove --purge edgeos-dnsmasq-blacklist"
leaves all the conf files in /etc/dnsmasq.d

I'm curious though, what does the cli option to "disable" actually do?

**Comment by jimr6007** [comment]
perhaps a regression of:
https://community.ubnt.com/t5/EdgeRouter/DNS-Adblocking-amp-Blacklisting-dnsmasq-Configuration/m-p/2260900#M198942

**Comment by britannic** [comment]
Confirmed issue, working on v1.1.6.11 to fix.

**Comment by britannic** [comment]
Fixed with v1.1.7.4.
